### ISSUE TITLE
Sem pasta lang

### ISSUE THREAD

**Issue by ghost** [TheBrazillianForgersTeam/DynamicCraft#2]
não dá pra traduzir sem pasta lang po zzzzz

**Comment by allanf181** [comment]
nem ta pronto ainda

**Comment by allanf181** [comment]
nem ta pronto ainda

**Comment by RRFreitas** [comment]
Primeiro vamos fazer o necessário para lançar a primeira versão, aí vai junto com a lang... :)

**Comment by ghost** [comment]
incompetência vem em bando
mindira boa çorte :stuck_out_tongue:
